### ISSUE TITLE
你好，请问支持的Android版本是多少呢？

### ISSUE THREAD

**Issue by acoolalien** [lvandroid/JniHook#1]
RT，我用模拟器验证了，x86 和 arm架构都hook失败了，不知道您那边情况如何。。。希望得到您的回复，祝好！

**Comment by lvandroid** [comment]
应该是ndk版本问题，我用的ndk-r14b, android用的7.1.1

**Comment by acoolalien** [comment]
Android 7的模拟器可以，低于7的就不行了，更换ndk版本也是不行。或者您那验证了真机是否可行吗。。我这里只有7的设备 汗。。
下面是7和5模拟器的日志：
09-01 08:28:28.565 7191-7191/com.bsty.jnihook E/ELFKooH: [+] Executable File or Shared Object, ElfHook Process..
09-01 08:28:28.566 7191-7191/com.bsty.jnihook D/ELFKooH: bbucket(1031), symndx(6), maskworks(127), shift2(13)
09-01 08:28:28.566 7191-7191/com.bsty.jnihook I/ELFKooH: [+] Search socket in /system/lib64/libc.so@0x7799704000 (gnu)
09-01 08:28:28.566 7191-7191/com.bsty.jnihook I/ELFKooH: [+] Found socket in /system/lib64/libc.so (0x24b18) 16
09-01 08:28:28.566 7191-7191/com.bsty.jnihook I/ELFKooH: [+] sym 0x7799709bc0, symidx 955.
09-01 08:28:28.581 7191-7191/com.bsty.jnihook I/ELFKooH: [+] old_func is 0x7799728b18, replace_func is 0x7794c3e208, new_func 0x7794c3e208.

09-01 08:21:06.456 10239-10239/com.bsty.jnihook E/ELFKooH: [+] Executable File or Shared Object, ElfHook Process..
09-01 08:21:06.457 10239-10239/com.bsty.jnihook D/ELFKooH: nbucket: 1031, nchain: 1361, bucket: 0xb6e3e3a8, chain:0xb6e3f3c4
09-01 08:21:06.457 10239-10239/com.bsty.jnihook I/ELFKooH: [+] sym 0xb6e36018, symidx 235.

**Comment by lvandroid** [comment]
这个库有些函数hook不到，推荐你另外个https://github.com/difcareer/AndroidInlineHook.git

**Comment by acoolalien** [comment]
好的，研究研究，谢谢！！！
